local regedit = require("regedit")

function keygen() -- If you do know a real algo let me know 😅
  local strings = {
    "MPJGX7J7777C777F7777", "9TFPTXCGXFMMXXR99DGT", "GJCCJHTWXKX9RDGPXTPC",
    "CD9CTD7GGTTXJFWPWJJ7", "99PMCWXJJGXFRCNWPPHR", "9RH7W9N9MG7JGK9PXWMF",
    "KPDKHFK7KTRG7D77TPND", "7CRHP79CWDWHJH9TNWGC", "7JFN9KDNGGGKHMPRJHH9",
    "7XD7XJTHCCMNK7TX7MHP", "HHWXGGD7G7PMRGFH9FDC", "H7MWTKKH7C77TRJHJP9F",
    "9P9FPJX9RNCJXHTXKJWF", "MGDNNRDCXCNFXFJNMGJF", "WTCP79FGKFHN P7CCXHHF",
    "RMTJRR7FCCRRTFWJGDKG", "WTWCJT79CJJHTXXMCRCP", "RHNJRPTDHWXPMRGMCPXF",
    "GDPWX7PCN9XFPFCD9PTM", "XWCGXHN9N7CPF9MNHPWG", "RGFKPKDWXJTXHFTNNXPT",
    "DTPKG9FDWJFJDXG9WRJ9", "JDK9RCXXDMFJCX9WW7WP", "T7DXXKNJW9XKPWJTWWRH",
    "XKK7CC7GRCFPF77WJTHF", "JHMKTG7D79WTGNNGTFPN", "9JCCHWNCRMFP79GCTNTR",
    "HC7TR7NWXXPMJX7DTKGT", "7KNNNHNDXK7PRNGWND9T", "K7HWPPRCRNPRRCKW9GRW",
    "RPDFCFTCHMKK7MRMW9N7", "GGJTRN9XW7XXG9DWFG7M", "RCDJ7FGKPGGJKJTGXNNK",
    "NNTJTGXFFKNC7DGM9R7K", "GNTRTNCM D9WMW9MKFXGW", "XRXF79CXWPXRW9G9GF9R",
    "TDP7WHHGRXFHTHWWXGKW", "KP9T7TTGCG9HWNNGTMCK", "TXNXTTJRJP9NFHRCGNMX"
  }
      
  local index = math.random(#strings)
  return strings[index]
end

local path = "SOFTWARE/id/Quake 4"
local current = regedit.QueryStringValue("HKLM", path, "CDKey")
if current == "" then
    local key = keygen()
    regedit.WriteStringValue("HKLM", path, "CDKey", key)
end
