local file = require("file")

function keygen()
    local charset = {"2", "3", "7", "a", "b", "c", "d", "g", "h", "j", "l", "p", "r", "s", "t", "w"}
    local key = ""
    for i = 1, 16 do
        key = key .. charset[math.random(#charset)]
    end
    return key
end

function getCurrentKey()
  local value, err = file.Read("baseq3/q3key")
  if err then
    return ""
  end

  local current = {}
  for line in value:gmatch("[^\r\n]+") do
      if not line:match("^//") then
          table.insert(current, line)
      end
  end
  return current[1]
end

local current = getCurrentKey()
if (current == "") then
  local arr = {}
  table.insert(arr, keygen())
  table.insert(arr, "// generated by quake, do not modify")
  table.insert(arr, "// Do not give this file to ANYONE.")
  table.insert(arr, "// id Software and Activision will NOT ask you to send this file to them.")
  local key = table.concat(arr, "\n")
  
  local err = file.Write("baseq3/q3key", key)
  if err then
    print(err)
  end
end
